### ISSUE TITLE
Allegiance crashes when switching to the loadout screen

### ISSUE THREAD

**Issue by LordBlacksun** [FreeAllegiance/Allegiance-AZ#3] opened 2015-08-29 11:17 UTC
I discovered that Allegiance crashes when trying to to switch to the load out screen,(pressing f4) in the hangar.
No error messages are shown, the game just freezes and quits
Tested at both 800x600 and 1080p.
The artwork is present in my 1.3 directory.

**Comment by BackTrak** [comment] 2015-08-29 16:19
should be fixed now. The issue is that miners and other drones don't get a wing ID. When a second player joins the game, they are shown the team screen. This screen tries to show the text name of the wing id. if the wing ID is -1 (Miner), then alleg crashes. Fix applied and pushed to AU.

**Comment by LordBlacksun** [comment] 2015-08-31 10:16
I just crashed under the same conditions as before, pressing f4 or clicking the load out screen, crashes alleg

**Closed as completed** 2015-09-15 08:08 UTC
Labels: bug
